apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xyo-appliance.fullname" . }}-config
  labels:
    {{- include "xyo-appliance.labels" . | nindent 4 }}
data:
  LOG_LEVEL_GATEWAY: {{ .Values.gateway.env.LOG_LEVEL | default "info" | quote }}
  LOG_LEVEL_ENRICHMENT: {{ .Values.enrichment.env.LOG_LEVEL | default "info" | quote }}
  LOG_LEVEL_LEXICON: {{ .Values.lexicon.env.LOG_LEVEL | default "info" | quote }}
  LOG_LEVEL_ANVIL: {{ .Values.anvil.env.LOG_LEVEL | default "info" | quote }}
  XYO_LOGOS_DIR: {{ .Values.persistence.logos.mountPath | default "/var/lib/xyo/logos" | quote }}
  XYO_ENRICHMENT_ADDR: "{{ include "xyo-appliance.fullname" . }}-enrichment:{{ .Values.enrichment.service.port }}"
  XYO_LEXICON_ADDR: "{{ include "xyo-appliance.fullname" . }}-lexicon:{{ .Values.lexicon.service.port }}"
  XYO_ANVIL_ADDR: "{{ include "xyo-appliance.fullname" . }}-anvil:{{ .Values.anvil.service.port }}"
