{{- if and .Values.persistence.logos.enabled (not .Values.persistence.logos.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "xyo-appliance.logosPvcName" . }}
  labels:
    {{- include "xyo-appliance.labels" . | nindent 4 }}
  {{- with .Values.persistence.logos.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.logos.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logos.size | default "10Gi" | quote }}
  {{- if .Values.persistence.logos.storageClass }}
  storageClassName: {{ .Values.persistence.logos.storageClass | quote }}
  {{- end }}
{{- end }}
