{{- if and .Values.global.licenseKey (not .Values.global.existingLicenseSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xyo-appliance.licenseSecretName" . }}
  labels:
    {{- include "xyo-appliance.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "xyo-appliance.licenseSecretKey" . }}: {{ .Values.global.licenseKey | quote }}
{{- end }}
---
{{- if and .Values.postgresql.enabled (not .Values.postgresql.external.enabled) (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xyo-appliance.fullname" . }}-postgres-secret
  labels:
    {{- include "xyo-appliance.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  postgres-user: {{ .Values.postgresql.auth.username | quote }}
  postgres-db: {{ .Values.postgresql.auth.database | quote }}
  dsn: {{ include "xyo-appliance.dbDsn" . | quote }}
{{- else if and .Values.postgresql.external.enabled (not .Values.postgresql.external.existingSecret) .Values.postgresql.external.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xyo-appliance.fullname" . }}-db-secret
  labels:
    {{- include "xyo-appliance.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.postgresql.external.dsn | quote }}
{{- end }}
