{{- if .Values.enrichment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xyo-appliance.fullname" . }}-enrichment
  labels:
    {{- include "xyo-appliance.componentLabels" (dict "root" . "component" "enrichment") | nindent 4 }}
  {{- with .Values.enrichment.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.enrichment.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.enrichment.service.port }}
      targetPort: {{ .Values.enrichment.service.targetPort | default 9091 }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "xyo-appliance.componentSelectorLabels" (dict "root" . "component" "enrichment") | nindent 4 }}
---
{{- end }}
{{- if .Values.lexicon.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xyo-appliance.fullname" . }}-lexicon
  labels:
    {{- include "xyo-appliance.componentLabels" (dict "root" . "component" "lexicon") | nindent 4 }}
  {{- with .Values.lexicon.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.lexicon.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.lexicon.service.port }}
      targetPort: {{ .Values.lexicon.service.targetPort | default 9092 }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "xyo-appliance.componentSelectorLabels" (dict "root" . "component" "lexicon") | nindent 4 }}
---
{{- end }}
{{- if .Values.anvil.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xyo-appliance.fullname" . }}-anvil
  labels:
    {{- include "xyo-appliance.componentLabels" (dict "root" . "component" "anvil") | nindent 4 }}
  {{- with .Values.anvil.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.anvil.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.anvil.service.port }}
      targetPort: {{ .Values.anvil.service.targetPort | default 9093 }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "xyo-appliance.componentSelectorLabels" (dict "root" . "component" "anvil") | nindent 4 }}
---
{{- end }}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xyo-appliance.fullname" . }}-postgres
  labels:
    {{- include "xyo-appliance.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.postgresql.service.port | default 5432 }}
      targetPort: {{ .Values.postgresql.service.targetPort | default 5432 }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "xyo-appliance.componentSelectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
{{- end }}
